from os import getenv

URL_PREFIX = "https://t.me/"
DEEPLINK_SUFFIX = "?start="

API_ID = getenv("API_ID")
API_HASH = getenv("API_HASH")

BOT_TOKEN = getenv("BOT_TOKEN")
BOT_UID = getenv("BOT_UID")
BOT_NAME = getenv("BOT_NAME")
BOT_URL = URL_PREFIX + BOT_UID
BOT_DEEPLINK = BOT_URL + DEEPLINK_SUFFIX

PUB_BOT_TOKEN = getenv("PUB_BOT_TOKEN")
PUB_BOT_UID = getenv("PUB_BOT_UID")
PUB_BOT_NAME = getenv("PUB_BOT_NAME")
PUB_BOT_URL = URL_PREFIX + PUB_BOT_UID
PUB_BOT_DEEPLINK = PUB_BOT_URL + DEEPLINK_SUFFIX

DEAL_BOT_TOKEN = getenv("DEAL_BOT_TOKEN")
DEAL_BOT_UID = getenv("DEAL_BOT_UID")
DEAL_BOT_NAME = getenv("DEAL_BOT_NAME")
DEAL_BOT_URL = URL_PREFIX + DEAL_BOT_UID
DEAL_BOT_DEEPLINK = DEAL_BOT_URL + DEEPLINK_SUFFIX

BOARD_ID = getenv("BOARD_ID")
BOARD_UID = getenv("BOARD_UID")
BOARD_NAME = getenv("BOARD_NAME")
BOARD_URL = URL_PREFIX + BOARD_UID

MEDIA_ID = getenv("MEDIA_ID")
MEDIA_UID = getenv("MEDIA_UID")
MEDIA_NAME = getenv("MEDIA_NAME")
MEDIA_URL = URL_PREFIX + MEDIA_UID

(TYPE_AUDIO,
 TYPE_DOCUMENT,
 TYPE_PHOTO,
 TYPE_VIDEO
 ) = range(4)
